server:
  port: 8080

spring:
  application.name: EquipmentSetCalculatorApplication
  datasource:
    url: jdbc:h2:file:./MonsterHunterDB
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
  h2:
    console.enabled: true
  sql:
    init:
      mode: embedded
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB